# Generated by Django 5.0.3 on 2024-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="birth_year",
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("", "Prefer not to say")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="health_condition",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
