# Generated by Django 5.0.3 on 2024-03-20 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "register",
            "0002_remove_customuser_birth_year_customuser_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="health_condition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="meal_images/")),
                ("analysis", models.JSONField()),
                ("day", models.DateField()),
                ("time", models.TimeField()),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
