# Generated by Django 5.0.3 on 2024-03-20 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0003_alter_customuser_health_condition_meal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="day",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="image",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="time",
        ),
        migrations.AddField(
            model_name="meal",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_image",
            field=models.ImageField(null=True, upload_to="meal_images/"),
        ),
        migrations.AddField(
            model_name="meal",
            name="segment_image",
            field=models.ImageField(null=True, upload_to="segment_images/"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
