# Generated by Django 5.0.3 on 2024-04-03 06:19

import register.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "register",
            "0004_remove_meal_day_remove_meal_image_remove_meal_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="meal_image",
            field=models.ImageField(
                null=True, upload_to=register.models.upload_path_original
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="segment_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=register.models.upload_path_segmented
            ),
        ),
    ]
